### PR TITLE
Adding join, toUpper, toLower and trim methods

### PR DESCRIPTION
**Pull request by ipeters90**

### CODE REVIEW

**Comment by cht8687** [comment]
Hi @ipeters90 , thank you for your contribution. It appears that those methods you added in are only available in Lodash. Could you double check it? if in that case, you might need follow the format of _.reverse, put Lodash only text and remove the underscore word in the comment. Finally, _.trim method on Chrome need 10.0?

**Comment by ipeters90** [comment]
@cht8687 you're right. those methods are Lodash only and I can definitely update. And according to w3schools, chrome support for trim is 10.0 but after further digging, 5.0+ seems to be the consensus.

**Comment by cht8687** [comment]
cheers! @ipeters90

**Comment by jdalton** [comment]
How deep do you want to go on these? For example the lodash trim method accepts a second param of `chars` to remove. At the moment the way you're presenting these methods, trim is just one example, is that built-ins are 1:1 to the lodash methods. However, in many cases lodash has features over the built-in.

**Comment by ipeters90** [comment]
I agree that it could be misinterpreted because Lodash extends the features of the built-in methods/API's and offers more options and flexibility for the developer so a 1:1 comparison won't be accurate, however, I think the purpose of this repo is mainly to demonstrate performing more basic tasks where native methods will work just fine.  For all my large projects that rely heavily on complex data structures I still choose to go with Lodash and would recommend anyone to do the same.

**Comment by jdalton** [comment]
> I agree that it could be misinterpreted because Lodash extends the features of the built-in methods/API's and offers more options and flexibility for the developer so a 1:1 comparison won't be accurate

I think that could be solved with a bit of disclaimer text. The tweet going around are "You don't need lodash". That combined with the examples which make it seem like 1:1 functionality it increases the likelihood of some devs getting a mixed signal.

**Comment by ipeters90** [comment]
I agree. Wording in the repo should be tweaked so that people understand some of the caveats that could come along with not having a library that handles all the normalizing, performance optimizations and extra features but show the use cases where it's perfectly acceptable or even beneficial to go native. Ultimately, it's up to @cht8687 :)

**Comment by jdalton** [comment]
> Ultimately, it's up to @cht8687 :)

It would be appreciated.

**Pull request merged**
