### PR TITLE
add _.after

### PR DESCRIPTION
**Pull request by infacq**

### CODE REVIEW

**Comment by jdalton** [comment]
You're just reimplementing lib at this point which kind of strays from the point of this project.

**Comment by infacq** [comment]
what do you mean

**Comment by jdalton** [comment]
You're simply re-implementing an `after` method with `Array#forEach`. It starts to drift from the message of not needing dependencies if you're re-implementing the methods in a slightly different way.

**Comment by infacq** [comment]
I don't get you. I just explain how to not using `_.after`

**Comment by jdalton** [comment]
Lodash is just JavaScript so yes you can implement it's methods in JavaScript. The point of this project is to show built-in equivalents not implementations of Lodash methods written with a dash more ES5/ES6 thrown in.

**Comment by infacq** [comment]
I just show the native implementation rather than use lodash/underscore. `_.after` it's not native

**Comment by cht8687** [comment]
hi @infacq,  thank you for your PR. Yes, @jdalton  is right about this list. We are not going to implementing functions at the moment. But I've created a [polls](https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/issues/25) to check if is good idea to have it. So let's just temporarily hold this PR and wait for others' voice. Cheers.

**Comment by infacq** [comment]
look forward the polls. I still believe to use native rather than load library file in a webpage

**Comment by cht8687** [comment]
@infacq  not so many people vote  though.  ( :sweat: )

**Comment by infacq** [comment]
look forward the polls. I still believe to use native rather than load library file in a webpage

**Pull request merged**
